### ISSUE TITLE
Cubbic or cubic?

### ISSUE THREAD

**Issue by swift502** [markusgod/cubic-octree#2]
First off, thanks for this. I'm surprised I found nothing on this concept except for this repository.

1. I'll try to port this into C# and extend it for my project. I see this is licensed under Apache 2. I understand that in this case I only have to keep the license file? But please let me know if there's other requirements by the license.

2. The real question is, why does the readme say Cubbic if the repository name says Cubic? 😄 What's the reasoning behind that? Which is the correct title?

**Comment by marknefedov** [comment]
1. You can license you're code however you want even under proprietary license, i'm glad this was helpful to you.
2. I can't spell things. :)

**Comment by swift502** [comment]
@markusgod Just an update. It seems to work great.

https://user-images.githubusercontent.com/24359130/114451000-02ab8080-9bd7-11eb-9516-06152d7c3646.mp4

**Comment by marknefedov** [comment]
Just curious, what rendering/gui toolkit you are using?

**Comment by swift502** [comment]
It's the Godot engine. I can only draw 3D lines to visualize something like this, but it's good enough.
